In [ ]:
import pandas as pd
import sqlite3
import os


from pathlib import Path
import sqlite3

PROJECT_ROOT = Path.cwd().parents[1]
print(PROJECT_ROOT)
conn1 = sqlite3.connect(PROJECT_ROOT / "database" / "logs.db")
conn2 = sqlite3.connect(PROJECT_ROOT / "database" / "metrics.db")

c:\Users\Lenovo\Desktop\AI-Observability-Platform

In [1]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]

for file in (PROJECT_ROOT / "database").iterdir():
    print(file.name)

connection.py
databse.db
logs.db
logs.sqbpro
metrics.db
metrics.py
migrations.py
repository.py
schema.py
template_repository.py
__pycache__

In [2]:
logs = pd.read_sql_query(
    "SELECT * FROM logs",
    conn1
)

metrics = pd.read_sql_query(
    "SELECT * FROM metrics",
    conn2
)

NameError: name 'pd' is not defined

In [ ]:
logs=pd.DataFrame(logs)
logs.head()

,id,timestamp,level,message,uuid,logger_name,raw_log,cluster_id,template,created_at
0,1,2026-07-27T13:40:38.308000,ERROR,Payment Success,4972176a-a567-4161-b8da-d70d96714dd3,41 root,"[2026-07-27 13:40:38,308] 41 root - ERROR - Pa...",NaN,None,2026-07-27 08:10:38
1,2,2026-07-27T13:40:40.309000,INFO,User Login,46559c0b-247b-4d3b-b147-a3c7ace5f0df,41 root,"[2026-07-27 13:40:40,309] 41 root - INFO - Use...",NaN,None,2026-07-27 08:10:40
2,3,2026-07-27T13:40:42.315000,INFO,User Login,f2b0e971-7d84-41ce-9bd1-3cbf48b3144e,41 root,"[2026-07-27 13:40:42,315] 41 root - INFO - Use...",NaN,None,2026-07-27 08:10:42
3,4,2026-07-27T13:40:44.316000,INFO,User Login,74e8e89a-219f-46ce-adeb-0f261fd4d770,41 root,"[2026-07-27 13:40:44,316] 41 root - INFO - Use...",NaN,None,2026-07-27 08:10:44
4,5,2026-07-27T13:40:46.317000,WARNING,Database Timeout,fb23cbee-442b-4d36-b93a-c70cd519afd7,41 root,"[2026-07-27 13:40:46,317] 41 root - WARNING - ...",NaN,None,2026-07-27 08:10:46

In [ ]:
metrics=pd.DataFrame(metrics)
metrics.head()

,id,timestamp,cpu_percent,memory_percent,disk_percent,network_sent,network_recv,process_count
0,1,2026-07-29 13:49:28.887158,27.7,86.9,84.1,194975277,1072830043,297
1,2,2026-07-29 13:49:31.908676,10.8,87.1,84.1,194975966,1072831312,297
2,3,2026-07-29 13:49:34.935429,4.3,87.2,84.1,194975966,1072831398,297
3,4,2026-07-29 13:49:37.958147,14.2,87.0,84.1,194976608,1072832122,295
4,5,2026-07-29 13:49:40.983529,15.0,87.7,84.1,194980373,1072832520,295

In [ ]:
print(logs.dtypes)
print(metrics.dtypes)